```{r, include=FALSE}

library (data.table)
library (ggplot2)
library (reshape2)
library (lubridate)
library (stringr)
library (caret)
library (gridExtra)

source ("../R/fetch.R")
source ("../R/features.R")
source ("../R/score.R")
source ("../R/utils.R")
source ("../R/cache.R")
source ("../R/customer-model.R")

# set global options for all code chunks
opts_chunk$set(fig.width=12, fig.height=8, tidy=T)
```



```{r}

train <- fetch (train = TRUE)

# extract a customer's attributes from the last quote they received
latest.quote <- train [ record.type == "shopping", .SD [ which.max (shopping.pt) ], by = customer.id ]
customers <- latest.quote [, c("customer.id", customer.attributes()), with = FALSE ]

# additional features
add.senior.driver (customers)
add.teen.driver (customers)
add.young.driver (customers)
add.married.with.children (customers)
add.population.density (customers)
add.customer.density (customers)
add.customer.density.by.location (customers)

# append each customer's purchases
extract.purchases (train, customers)

# split the data for CV
train.index <- sample (1:nrow (customers), .80 * nrow (customers))
test  <- customers [ -train.index ]
train <- customers [  train.index ]

# which model parameters will be tuned?
tune.grid <- expand.grid (
  n.trees           = c(50, 100, 200), 
  shrinkage         = 0.1,
  interaction.depth = c(1, 5, 9))

# fields used for predictions - kind of fugly
predictors <- non.options (train) 
predictors <- setdiff (predictors, c("customer.id", "location", "state"))

# remove any missing values before training
train <- train [ complete.cases (train) ]

# tune/train a separate model for each option
#models <- lapply ("option.b", function (option) {
models <- lapply (options(), function (option) {
  train (
    method    = "gbm", 
    tuneGrid  = tune.grid,
    trControl = trainControl (method = "cv", number = 2),
    y         = train [[ option ]],
    x         = train [, predictors, with = F] )
  })

# name each of the models in the list
names(models) <- options.hat()

# make a prediction for each option [a-g] using the correct model
for (option.hat in names (models)) {
  m <- models [[option.hat]]
  test [, option.hat := predict (m, .SD), .SDcols = predictors, with = FALSE ]
}

# score the results
accuracy.score (test)
partial.accuracy.score (test)

```

