Kaggle Allstate Purchase Prediction Competition
========================================================

Of course, start out by loading the source data sets.

```{r fetch.data,message=FALSE}
library(randomForest)
library(caret)
source ("../R/fetch.R")
source ("../R/utils.R")
source ("../R/features.R")
train <- fetch()
add.plan(buy)
```


Frequency of Each Plan Variation

``` {r count.plans}

#train[, plan := paste0(option.a,option.b,option.c,option.d,option.e,option.f,option.g)]
ct.prod <- train[, list(ct = length(customer.id)),by=plan]
ggplot(ct.prod,aes(ct))+geom_histogram()

ggplot(ct.prod,aes(ct))+stat_ecdf()


```

Build "Naive" Model Based only on Customer Attributes & Purchase Points
========================================================================

```{r cust.model,message=FALSE}
buy <- train[record.type == "purchase"]


# create a train and test set
train.index <- createDataPartition(y= buy$plan, p=.80,list=FALSE)
train <- buy[train.index]
test  <- buy[-train.index]

# defines how the parameter tuning will occur
control <- trainControl (method = "cv", number = 2)

# which model parameters will be tuned?
tune.grid <- expand.grid (
  ntree           = c(100, 200), 
  mtry         = c(2,4,6,8,10)


models <- lapply(options(), function(option) {
  train(
    method    = "rf",
    trControl = control,
    y         = "", #Still need to finish this
    x         = "", #Still need to finish this
    tuneGrid  = tune.grid)
})
  
# # Build String Containing Model Specification Formula: y ~ x1 + x2 + ...
# form <- as.formula(paste0("option.a~",paste("day.of.week",
#                                  "time.of.day.hours",
#                                  #"state",
#                                  #"location",
#                                  "group.size",
#                                  "homeowner",
#                                  "car.age",
#                                  "car.value",
#                                  "risk.factor",
#                                  "age.oldest",
#                                  "age.youngest",
#                                  "married.couple",
#                                  "option.c.previous",
#                                  "duration.previous",sep='+')))

fit.a <- randomForest(form, data= buy, ntree = 100,na.action=na.omit)


```


