```{r, include=FALSE}

library (data.table)
library (ggplot2)
library (reshape2)
library (lubridate)
library (stringr)

source ("../R/fetch.R")
source ("../R/features.R")
source ("../R/models.R")

# set global options for all code chunks
opts_chunk$set(fig.width=12, fig.height=8, tidy=T)
```

Kaggle Allstate Purchase Prediction Competition
========================================================

Contains analysis around modeling for the Kaggle Allstate competition.

### Q. What would a naive model look like in this case?

A naive model would simply predict the most popular choice for each option.

```{r}
train <- fetch()

# the prediction for 'option.x' will be called 'option.x.hat'
options <- na.omit (str_extract (names (train), "option.[a-g]$"))
options.hat <- paste0 (options, ".hat")

# train and predict the options with the naive model
model <- naive.model (train)

# TODO why is the R session blowing chunks on this assignment?
train [, options.hat := predict (model, newdata = train)]
```

